nextrandom = true --UBAH JADI FALSE JIKA GAMAU JOIN RANDOM WORLD SEBELUM NEXT WORLD
randomworld = {"XKGWHL","QJDFEM","ASZCVR","YIRBNX","UOTLFP","HMJAVO","KXNZPS","UWGTCI","LEORBY","NPQXZM","FDUKSA","VMXJYG"}
