DelayRecon = 4 * 60000 --JEDA RECONNECT
randomworld = {"BUBUHWORLD1","BUBUHWORLD2","BUBUHWORLD3","BUBUHWORLD4","BUBUHWORLD5","BUBUHWORLD6","BUBUHWORLD7","BUBUHWORLD8","BUBUHWORLD9","BUBUHWORLD10","BUBUHWORLD11","BUBUHWORLD12"}
